# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for client
  pod 'TesseractOCRiOS', '4.0.0'

  target 'client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'client-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for client-tvOS

  target 'client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


